name: wrap
description: Chain style programming syntax sugar utilities for flutter widgets.
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  analyzer: ^6.11.0
  annotate_wrap: ^0.0.0
  build: ^2.4.2
  build_name: ^0.0.0
  build_type: ^0.0.0
  child_type: ^0.0.0
  compat_utils: ^0.0.0
  flutter: { sdk: flutter }
  meta: ^1.16.0
  nest_gen: ^0.0.0
  path: ^1.9.1
  source_gen: ^2.0.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test: { sdk: flutter }
