name: work_trace
description: The WorkTrace library for client storage and local operations.
version: 0.0.0
resolution: workspace
environment: { sdk: ^3.6.0, flutter: "^3.27.0" }

dependencies:
  auto_stories: ^0.0.0
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }
