name: workspace
description: Workspace management scripts, encapsulate the entries.
publish_to: none
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.7.0

dependencies:
  compat_utils: ^0.0.0
