name: workspace
description: Workspace management scripts, encapsulate the entries.
publish_to: none
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  compat_utils: ^0.0.0
