semi: false

# Toml plugin might incompatible with VSCode extension,
# so that it's not installed inside node.
plugins:
  - prettier-plugin-sh

# Special rules.
overrides:
  - { files: "*.jsonc", options: { trailingComma: "none" } }
