name: worktrace_monorepo
version: 0.0.0
publish_to: none
environment: { sdk: ^3.7.0}

workspace:
  # Application components.
  - apps/flutter
  - brand/flutter
  - packages/work_trace

  # Shared libraries for code reuse.
  - packages/auto_stories
  - packages/avoid_nullable
  - packages/compat_utils
  - packages/custom_app
  - packages/data_gen
  - packages/inherit
  - packages/modifier
  - packages/smooth_ui
  - packages/state_reuse
  - packages/workspace_utils
  - packages/wrap

dependencies:
  auto_stories: ^0.0.0
  workspace_utils: ^0.0.0
