name: worktrace_monorepo
version: 0.0.0
publish_to: none
environment: { sdk: ^3.6.0 }

workspace:
  - apps/flutter
  - packages/auto_stories
  - packages/auto_stories_compat
  - packages/auto_stories_dev
  - packages/work_trace

dependencies:
  auto_stories_dev: ^0.0.0
