name: worktrace_monorepo
version: 0.0.0
publish_to: none
environment: { sdk: ^3.6.0 }

workspace:
  # Application and code components.
  - apps/flutter
  - packages/work_trace
  - packages/work_trace_ui

  # Development toolkit and command-line tool.
  - packages/auto_stories
  - packages/auto_stories_anno
  - packages/auto_stories_dev

  # Utilities and code reuse.
  - packages/avoid_nullable
  - packages/inherit
  - packages/modifier
  - packages/paint_graph
  - packages/smooth_ui
  - packages/state_reuse
  - packages/syntax_sugar
  - packages/wrap

dependencies:
  auto_stories_dev: ^0.0.0
  work_trace_ui: ^0.0.0
