name: worktrace_monorepo
description: Workspace management package at the root of the WorkTrace monorepo.
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.8.0-278.1.beta

workspace:
  # Application components.
  - apps/flutter
  - brand/flutter

  # Framework libraries.
  - packages/work_trace
  - packages/auto_stories

  # Builder package annotations.
  - packages/annotate_data
  - packages/annotate_lerp
  - packages/annotate_name
  - packages/annotate_type

  # Builder packages.
  - packages/build_data
  - packages/build_lerp
  - packages/build_name
  - packages/build_type

  # Toolkit packages as ecosystem.
  - packages/child_types
  - packages/compat_utils
  - packages/concise_cli
  - packages/custom_app
  - packages/nest_gen
  - packages/nest_run
  - packages/paint_out
  - packages/smooth_ui
  - packages/state_reuse
  - packages/wrap

dependencies:
  auto_stories: ^0.0.0
  nest_run: ^0.0.0
