name: worktrace_monorepo
description: Workspace management package at the root of the WorkTrace monorepo.
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.7.0

workspace:
  # Application components.
  - apps/flutter
  - brand/flutter
  - packages/work_trace

  # Shared libraries for code reuse.
  - packages/auto_stories
  - packages/compat_utils
  - packages/custom_app
  - packages/data_build
  - packages/inherit
  - packages/smooth_ui
  - packages/state_reuse
  - packages/wrap

  # Workspace management scripts.
  - scripts/workspace_dart

dependencies:
  auto_stories: ^0.0.0
  workspace: ^0.0.0
