targets:
  $default:
    builders:
      build_lerp|register_lerp_builder: { enabled: true }
      build_lerp|lerp_builder:
        enabled: true
        options: { depends: [build_lerp|register_lerp_builder] }

builders:
  lerp_builder:
    import: package:build_lerp/builder.dart
    builder_factories: [lerpBuilder]
    build_extensions: { ".dart": [".lerp.g.dart"] }
    auto_apply: none
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

  register_lerp_builder:
    import: package:build_lerp/builder.dart
    builder_factories: [registerLerpBuilder]
    build_extensions: { ".dart": [".register.g.dart"] }
    auto_apply: none
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
