targets:
  $default:
    builders:
      build_name|name_builder: { enabled: true }
      build_lerp|lerp_builder:
        enabled: true
        options: { depends_on: [build_name|name_builder] }

# Yaml anchor syntax is unsupported in build.yaml.
builders:
  lerp_builder:
    import: package:build_lerp/builders.dart
    builder_factories: [lerpBuilder]
    build_extensions: { ".dart": [".lerp.g.dart"] }
    auto_apply: none
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
