name: auto_stories_dev
description: Command-line tools for development with the auto_stories framework.
version: 0.0.0
resolution: workspace
environment: { sdk: ^3.6.0 }

dependencies:
  auto_stories_compat: ^0.0.0

dev_dependencies:
  test: ^1.24.0
