name: annotate_lerp
description: Annotations about how to build lerp with package:build_lerp.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0

dependencies:
  build_name: ^0.0.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.15
