name: annotate_type
description: Annotations about how to build types with package:build_type.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  build_name: ^0.0.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.15
