name: custom_app
description: Customizable app framework without material or cupertino.
version: 0.0.0
resolution: workspace
environment: { sdk: ^3.6.0, flutter: "^3.27.0" }

dependencies:
  avoid_nullable: ^0.0.0
  flutter: { sdk: flutter }
  state_reuse: ^0.0.0
  wrap: ^1.0.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  modifier: ^0.0.0
