name: custom_app
description: Customizable app framework without material or cupertino.
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0 <4.0.0"

dependencies:
  avoid_nullable: ^0.0.0
  flutter: { sdk: flutter }
  inherit: ^0.0.0
  smooth_ui: ^0.0.0
  state_reuse: ^0.0.0
  wrap: ^1.0.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  modifier: ^0.0.0
