name: compat_utils
description: Compatible utilities between package:flutter and package:analyzer.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  args: ^2.6.0
  path: ^1.9.1
  pub_semver: ^2.1.5
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  test: ^1.24.0
