name: worktrace_brand
description: Paint brand effects such as logo and banner of WorkTrace.
version: 0.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0-278.1.beta
  flutter: ">=3.32.0-0.2.pre <4.0.0"

dependencies:
  flutter: { sdk: flutter }
  wrap: ^1.0.0

dev_dependencies:
  flutter_test: { sdk: flutter }
