name: auto_stories_compat
description: Compatible utilities between package:flutter and package:analyzer.
version: 0.0.0
resolution: workspace
environment: { sdk: ^3.6.0 }

dependencies:
  html: ^0.15.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
