name: data_gen
description: Generate common boilerplates for data classes automatically.
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^6.11.0
  build: ^2.4.2
  compat_utils: ^0.0.0
  meta: ^1.15.0
  path: ^1.9.0
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.15
  test: ^1.24.0
