name: name_gen
description: Generate name of classes and fields to assist further code-gen.
version: 0.0.0
resolution: workspace
environment: { sdk: ^3.6.0 }

dependencies:
  analyzer: ^6.11.0
  meta: ^1.15.0
  path: ^1.9.0

dev_dependencies:
  test: ^1.24.0
