// Generated by dts-bundle-generator v9.5.1

export interface ExportPaths {
	/**
	 * This field is not defined in package.json specification,
	 * but required by this package to tell the compiler where the entry is.
	 */
	source: string;
	cjs: string;
	esm: string;
	dts: string;
}
/**
 * There might be one or more layer of export path defines.
 * @param root path to the root folder where package.json locates.
 */
export declare function parseExportPaths(root: string): ExportPaths[];

export {};
