name: worktrace
version: 0.0.0+0
publish_to: none
resolution: workspace
environment: { sdk: ^3.6.0, flutter: ">=3.27.0 <4.0.0" }

dependencies:
  auto_stories: ^0.0.0
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: false
