name: worktrace
version: 0.0.0+0
publish_to: none
resolution: workspace
environment: { sdk: ^3.7.0, flutter: ">=3.29.0 <4.0.0" }

dependencies:
  auto_stories: ^0.0.0
  flutter: { sdk: flutter }
  go_router: ^14.6.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: false
