name: state_reuse
description: Code reuse utilities for data binding of stateful widgets.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }
  wrap: ^1.0.0

dev_dependencies:
  flutter_test: { sdk: flutter }
