name: state_reuse
description: Code reuse utilities for data binding of stateful widgets.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  build_data: ^0.0.0
  build_lerp: ^0.0.0
  compat_utils: ^0.0.0
  flutter: { sdk: flutter }
  wrap: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test: { sdk: flutter }
