name: auto_stories
description: Auto generate widget preview with minimal configurations.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  args: ^2.6.0
  build_data: ^0.0.0
  build_lerp: ^0.0.0
  compat_utils: ^0.0.0
  custom_app: ^0.0.0
  flutter: { sdk: flutter }
  flutter_web_plugins: { sdk: flutter }
  smooth_ui: ^0.0.0
  state_reuse: ^0.0.0
  wrap: ^1.0.0

dev_dependencies:
  flutter_test: { sdk: flutter }
