name: nest_gen
description: Generator abstraction helpers for non-top-level annotations.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0

dependencies:
  analyzer: ^6.11.0
  build: ^2.4.2
  compat_utils: ^0.0.0
  meta: ^1.16.0
  source_gen: ^2.0.0

dev_dependencies:
  test: ^1.24.0
