builders:
  name_builder:
    import: package:build_name/builders.dart
    builder_factories: [nameBuilder]
    build_extensions: { ".dart": [".name.g.dart"] }
    auto_apply: none
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
