name: smooth_ui
description: Animated layout and effects to make Flutter app smooth and elegant.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0 <4.0.0"

dependencies:
  compat_utils: ^0.0.0
  data_build: ^0.0.0
  flutter: { sdk: flutter }
  inherit: ^0.0.0
  state_reuse: ^0.0.0
  wrap: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test: { sdk: flutter }
