name: smooth_ui
description: Animated layout and effects to make Flutter app smooth and elegant.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0-278.1.beta
  flutter: ">=3.32.0-0.2.pre <4.0.0"

dependencies:
  compat_utils: ^0.0.0
  data_build: ^0.0.0
  flutter: { sdk: flutter }
  state_reuse: ^0.0.0
  wrap: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test: { sdk: flutter }
