name: smooth_ui
description: Animated layout and effects to make Flutter app smooth and elegant.
version: 0.0.0
resolution: workspace
environment: { sdk: ^3.6.0, flutter: "^3.27.0" }

dependencies:
  avoid_nullable: ^0.0.0
  compat_utils: ^0.0.0
  flutter: { sdk: flutter }
  state_reuse: ^0.0.0
  wrap: ^1.0.0

dev_dependencies:
  flutter_test: { sdk: flutter }
