targets:
  $default:
    builders:
      data_build|name_builder: { enabled: true }
      data_build|type_builder: { enabled: true }

# Yaml anchor syntax is unsupported in build.yaml.
builders:
  data_builder:
    import: package:data_build/builders.dart
    builder_factories: [dataBuilder]
    build_extensions: { ".dart": [".data.g.dart"] }
    auto_apply: none
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

  name_builder:
    import: package:data_build/builders.dart
    builder_factories: [nameBuilder]
    build_extensions: { ".dart": [".name.g.dart"] }
    auto_apply: none
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

  type_builder:
    import: package:data_build/builders.dart
    builder_factories: [typeBuilder]
    build_extensions: { ".dart": [".type.g.dart"] }
    auto_apply: none
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

  copy_builder:
    import: package:data_build/builders.dart
    builder_factories: [copyBuilder]
    build_extensions: { ".dart": [".copy.g.dart"] }
    auto_apply: none
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

  lerp_builder:
    import: package:data_build/builders.dart
    builder_factories: [lerpBuilder]
    build_extensions: { ".dart": [".lerp.g.dart"] }
    auto_apply: none
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
