builders:
  data_builder:
    import: package:data_build/builders.dart
    builder_factories: [dataBuilder]
    build_extensions: { ".dart": [".data.g.dart"] }
    auto_apply: root_package
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
