name: data_build
description: Generate common boilerplates for data classes automatically.
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^7.3.0
  compat_utils: ^0.0.0
  meta: ^1.15.0
  path: ^1.9.0

dev_dependencies:
  test: ^1.24.0
