name: data_build
description: Generate common boilerplates for data classes automatically.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^6.11.0
  compat_utils: ^0.0.0
  meta: ^1.15.0
  path: ^1.9.0

dev_dependencies:
  test: ^1.24.0
