name: paint_svg
description: An abstract layer to support both Flutter canvas and svg output.
version: 0.0.0
resolution: workspace
environment: { sdk: ^3.6.0, flutter: "^3.27.0" }

dependencies:
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }
