name: nest_run
description: Run commands and scripts in nested child packages in workspace.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  path: ^1.9.1

dev_dependencies:
  test: ^1.24.0
