name: nest_run
description: Run commands and scripts in nested child packages in workspace.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  args: ^2.7.0
  compat_utils: ^0.0.0
  concise_cli: ^0.0.0
  path: ^1.9.1
  pub_semver: ^2.1.5
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  test: ^1.24.0
