name: avoid_nullable
description: Utilities to avoid unnecessary nullable to improve performance.
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }
