name: workspace_utils
description: Utilities for Dart workspace bulk operations on multiple packages.
version: 0.0.0
resolution: workspace
environment: { sdk: ^3.6.0 }

dependencies:
  args: ^2.6.0
  compat_utils: ^0.0.0
  path: ^1.9.0
  pub_semver: ^2.1.5
  yaml: ^3.1.3

dev_dependencies:
  test: ^1.24.0
