name: annotate_name
description: Annotations about how to build names with package:build_name.
resolution: workspace
version: 0.0.0

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  meta: ^1.16.0

dev_dependencies:
  test: ^1.24.0
